### PR TITLE
Pump changes

### PR DESCRIPTION
**Pull request by blowfishpro**
* Fuel pumps must now be present and active in order to avoid boiloff during prelaunch (previously being on the launch pad was enough)
* Fuel pumps are now enabled by default and enabled setting respects symmetry in the editor
* Streamline fuel pump enable/disable UI - now a simple button rather than display + button

### CODE REVIEW

**Comment by Starwaster** [comment]
I haven't actually played using these changes and haven't finished going over all the changes but it looks like you're moving temperature clamping and associated minimum temperature calculation all into the fuel pump code. A problem here is that in the fuel pump code, you're running a very simplified check against the tank's loss_rate. The problem with that is that loss_rate is used by the old boiloff method. There are a few tanks that still use it, but the four main cryogenic fuels do not, so unless I'm missing something in the code, they're not going to have their temperature's adjusted. The code should also be checking against the tank's vsp value being greater than 0. This is the resource's latent heat of vaporization and supercedes loss_rate)

**Comment by blowfishpro** [comment]
I didn't touch that part of the code, but you may be right.  I'll look into fixing that.  Boiloff is explicitly disabled when attached to launch clamps though, so it may not make a huge difference.

**Comment by Starwaster** [comment]
I didn't realize temperature clamping in the fuel pumps was that old. I thought it was a recent change but apparently it was being done in both ModuleFuelTanksRF and RefuelingPump. Your changes removed that from MFTRF so now it's only being done at the pump, and the pump doesn't check properly.

But yes, the temperature clamping makes a difference. If launch pad tank temperature doesn't get addressed then when the rocket launches you will get a very high spike in boiloff on liftoff until the equilibrium is reached. That won't matter much for the first stage but for payload stages like S-IVB, Centaur or SLS, et al, it's going to be painful for some people.

Arguably, clamping the temperature to the boiling temp isn't realistic but  at least it doesn't have the associated spike. Probably it would be more realistic to not clamp the temperature at all, let boiloff happen and refill with the pump. That way you get a more natural cooling effect that doesn't  spike drastically when you launch. 

Or maybe  let the boiloff code proceed just enough to calculate the cooling done from the mass loss but then not actually remove resource. (i.e. move your line 133 checks to  219 but only prevent the tank amount loss instead of breaking out)

**Comment by blowfishpro** [comment]
I see.  Do you think this is serious enough to warrant a fresh release for KSP 1.2.2 as well?

**Comment by NathanKell** [comment]
Yes. I thought you were doing the temperature cleaning, as we discussed
when you started looking into doing this change...

**Comment by NathanKell** [comment]
Clamping*

I hate phone keyboards

**Comment by blowfishpro** [comment]
There is code in the launch clamps to set the temperature of the tank, but apparently it is not working correctly as Starwaster mentioned.  I didn't think to check it because it was there before these changes.

**Comment by NathanKell** [comment]
(I say yes because the losses from a hydrolox tank will be quite severe...)

On Jul 7, 2017 5:03 PM, "NathanKell" <nathankell@gmail.com> wrote:

Clamping*

I hate phone keyboards

**Pull request merged**
