### PR TITLE
Added GUI Styles and updated Engine and Tank editor GUIs

### PR DESCRIPTION
**Pull request by jwvanderbeck**
Added a couple GUI styles based on TestFlight's style.  Setup the Tank and Engine GUIs to use these for panels and tooltips.

This makes the windows and more importantly the Tooltips about a billion times easier to actually read.

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
Here is what it looks like: http://imgur.com/a/OUQrN

**Comment by Starwaster** [comment]
Is that color scheme user configurable? It's kind of garish and clashes with the stock GUI. (sorry, that's how it appears to me)

**Comment by jwvanderbeck** [comment]
It clashes with the stock style but it is much better :D  It is based on the same styles I used in TestFlight which in turn on based on scientifically designed color palettes for optimum readability, and less eye strain.

Of course it can be changed, but when I did it @NathanKell said he liked the TF style and was happy to use that same look.

At the end of the day though it is whatever people want.  Though IMHO anything that is not stock style is instantly better.

**Comment by NathanKell** [comment]
I for one like that style a lot.

**Comment by NathanKell** [comment]
@jwvanderbeck is it user configurable? Could it be, in RealSettings say? As I said I like it a lot, but...configurability <3

**Comment by jwvanderbeck** [comment]
Possibly.  The numbers in the Styles class could be driven by a config, but you would have to refactor things slightly since it is currently set up as a Static class for ease of use.

**Comment by taniwha** [comment]
Thank you

**Pull request merged**
