### PR TITLE
Missing tanks for stock, RetroFuture, and SXT

### PR DESCRIPTION
**Pull request by ImAHungryMan**
Hello,

Please let me know if I messed up. Here's a list of things I did:

-Multiplied the RSCapsuledyne's tank by 5 to be more in line with other RF tanks
-Added a bunch of missing Squad Mk3 parts/adapters as Fuselages
-Added a missing Mk IV tank as Fuselage
-Added a couple SXT parts as Fuselages

Question:  How does one go about determining which tanks should be Default/Cryogenic/BalloonCryo/etc.? I know Fuselage/Xenon/ServiceModule is pretty self-explanatory but what about the rest?

For your consideration.

### CODE REVIEW

**Comment by NathanKell** [comment]
Thanks so much for this!
For determining what's what, if a tank looks like a normal tank, it should be Default. If has visible insulation it should be Cryogenic. If it is quite light compared to other tanks (low dry mass for its fuel mass) then it should be classed as Balloon (for normal propellants) or BalloonCryo (if obviously insulated, like the Shuttle External Tank).

However, you will not go far wrong ignoring the existence of Balloon and BalloonCryo, few real life tanks have ever been such.

**Comment by ImAHungryMan** [comment]
Ah so eyeball it. Gotcha :)

I ask that because I noticed that NovaPunch's tanks are all set to default even though they are called "Insulated Fuel Tanks" in-game.

Also, I want to add support to new tanks from Fuel Tanks Plus and Munar Industries. However, what I like to do is make tanks with "interesting shapes" Cryogenic. My reasoning is that this allows for more options when constructing a space-going vessel. 

If you don't consider this very "realistic", I understand and I'll keep the configs to myself.

**Comment by NathanKell** [comment]
Then it might be worth changing NP's tank types. Good catch!
I have to admit, I only use Procedural Part tanks, so I rely on others' opinions regarding mods' tank parts. :) -- so, well, if you're going to be the major user of those parts, and you think they "make more sense" as cryo, that's fine.

**Comment by ImAHungryMan** [comment]
Great! I'll soon send a pull request to that effect.

And Procedural Parts sounds like a good idea actually. Might switch to it,
at least partially.

Thanks.

**Comment by NathanKell** [comment]
Well, I'm going to accept this one for now, and the next one can be for next RF. :)

**Pull request merged**
