### PR TITLE
NF Spacecraft, Construction Configs

### PR DESCRIPTION
**Pull request by Tellion**

### CODE REVIEW

**Comment by NathanKell** [comment]
Thanks!

**Comment by Tellion** [comment]
My pleasure! If you have the time, I would appreciate your advice on NFP - what I have so far is on the last two pages of the RF thread.

**Comment by NathanKell** [comment]
Will do!

**Comment by NathanKell** [comment]
@Tellion if the existing ElectricPropulsion tank type doesn't have the correct dry mass ratios or pressurization of the gases, we can add a new tank type or you can override the basemass and utilization. That'll take a fair amount of research as to just how heavy real tanks are for probes, and what level of compression the gases are under.

**Comment by Tellion** [comment]
Oh, I did not doubt RF's definitions, nor do I have the knowledge to atm. What I am unsure about with regards to patching the NFP tanks is what I should do with the volumes. Using RF tank types will ensure balance with regards to wet/dry mass ratios, but volumes seem to be all over the place. Should I attempt to get them close to that of PP tanks for all NFP tanks (that would in some cases make no sense visually, but then again, having an Argon tank of equal size but more capacity than a Xenon tank might raise eyebrows as well), or are we fine with it being somewhat disorderly as long as everything is balanced mass wise?

**Comment by NathanKell** [comment]
@Tellion whoops, missed this. What you should do is, indeed, measure the volume with a ppart set to 100% utilization. Compression of various gases differs so in practice you might well be able to stuff more or less of a gas in a tank, but the physical liters of volume should be correct. :)

**Comment by Tellion** [comment]
No worries :) Will do, thanks. This eyeballing will get a little imprecise with radials, also parts of equal dimensions but visually different tank volume (as with the large argon/xenon tanks, http://imgur.com/a/mUxBC#4 )  will have the same volume in the end - but given that they both use the same tank type it probably is the best solution.

**Comment by NathanKell** [comment]
You can actually perfectly replicate those with a central procedural cylinder and then radial attach proc tanks set to fillet cylinder with equal diameter, length, and fillet (that makes a sphere).

**Pull request merged**
