### PR TITLE
Make sure cost only gets multiplied by scale once

### PR DESCRIPTION
**Pull request by SirKeplan**
Fixes issues with SSTUModularEngineCluster pricing.

### CODE REVIEW

**Comment by SirKeplan** [comment]
@NathanKell poke?

**Comment by jobadiah08** [comment]
I am seeing this bug. Using RF v12.0.1. A cluster of 8 SSTU H-1B engines costs ~$70,000. 
Appears to be using: Cost = (BasePrice+UpgradeCost)*EngineCount
where UpgradeCost is equal to the cost to upgrade all the engines in the cluster. So if an engine costs $1000, $1000 to upgrade, and you have 5 engines
Cost = (1000 + 5000)*5 = $30000
It should  be: Cost = 1000*5 +5000 = 10000 (BasePrice*EngineCount + Upgrade Cost)

Playing on 1.2.2 with RO/RP-0

**Comment by SirKeplan** [comment]
@jobadiah08 are you using my patch? because i am seeing the cost going up exactly the same way as with placing multiple single engines. (cost of 14,000 for 8)

This is with the latest RF, RP-0, RO and SSTU

**Comment by jobadiah08** [comment]
I am using the latest version from github of real fuels. Is there a separate patch I should also be using?

**Comment by stratochief66** [comment]
@NathanKell poke. 

this is also referenced over in RP-0
https://github.com/KSP-RO/RP-0/issues/538

**Comment by blowfishpro** [comment]
Well, Tweakscale integration is broken anyway, it seems like the risk is relatively low.  And if it fixes SSTU issues, I'm for it

**Pull request merged**
