### PR TITLE
Port nextRP0 to KSP 1.3.1

### PR DESCRIPTION
**Pull request by aw1621107**
Hopefully caught everything...

### CODE REVIEW

**Comment by aw1621107** [comment]
Updated to master for KSP 1.3.1

**Comment by blowfishpro** [comment]
This branch has merge conflicts which need to be resolved.  It might just be best to rebase the original branch off of master (although this will probably require some git-foo as well)

**Comment by aw1621107** [comment]
Alright, done, I think

**Comment by blowfishpro** [comment]
@Starwaster did you want to make any more changes to `newCryo` or is this good to merge?

**Comment by Starwaster** [comment]
Oh it is going to require more coding before it goes into production.

**Comment by aw1621107** [comment]
Should I take out the newCryo commits so we can at least get the RP-0 changes merged?

**Comment by blowfishpro** [comment]
@aw1621107 makes sense to me

**Comment by aw1621107** [comment]
Alright, done. Can't rename the branch without creating a new PR, unfortunately.

**Comment by aw1621107** [comment]
Looks like there might be some non-newCryo changes that aren't in the nextRP0 branch, but in the newCryo branch, namely 94e063f8a07f (Fix utilization clamping) and 5bfd8a65d396 (Fix ECMs applying before parts are purchased). Should I cherry-pick those to this PR? If I do, the newCryo branch will need to be rebased.

**Comment by NathanKell** [comment]
@aw1621107 yep those should be in nextRP0. The thing was, part way through making nextRP0 I realized we needed selectable insulation for RP-1's tank system to work. That meant there wasn't a point to keep working on nextRP0 since the new RP-1 would require newCryo anyway. So that's why the commits are there.

If we want to get RP-1 out before newCryo is ready then (1) we need to cheery-pick, yeah, and (2) we need to create a *lot* of new tanks since we won't be able to vary insulation per-tank.

**Comment by Starwaster** [comment]
Well you'll be able to configure how many layers of MLI there are, up to 100

**Comment by NathanKell** [comment]
@Starwaster  \o/ That's the main thing RP-1 needs, yep!

@blowfishpro final thoughts? (LGTM)

**Pull request merged**
