### PR TITLE
[Mod Support] Update for the KSP 1.4 tanks

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Add the new Rockomax and toroidal tank patches as subsets of the old ones (identical parts).
* Add patches for the new spherical and capsule tanks.
* Add patch for the missed NCS Adapter tank.

**Notes:**

* Volumes were calculated based upon the model mesh dimensions and adjusted to be 86% of the overall tank volume. This may be a completely wrong assumption though so some feedback is required.

### CODE REVIEW

**Comment by blowfishpro** [comment]
Seems good to me.  If no one has any objections within a couple of days feel free to poke me and I'll merge it

**Comment by PhineasFreak** [comment]
Did anyone double-check these in-game?

**Comment by PhineasFreak** [comment]
I set that utilization value because this is the standard Procedural Parts utilization. But now, as @Starwaster mentions, i realize that this is only valid for PP tanks and not fixed ones. Still, i do not think that it is possible to utilize 100% of the model volume since we are expecting bladders and other hardware that are included inside the tank (at least for the smaller ones).

**Comment by Starwaster** [comment]
@PhineasFreak FYI that's not a Procedural Parts thing, that's a Modular Fuels thing (and by extension RF) defined in MFSSETTINGS (MFSSettings.cfg) - and 86% is a hard penalty to impose for any tank that then runs the risk of another 86% penalty imposed by MFT. That may or may not have the tweakable exposed in the UI.

**Comment by blowfishpro** [comment]
It's generally up to the user to choose a sane utilization, although I think 85% is reasonable as the default

**Comment by NathanKell** [comment]
RF expects volume equal to the entire volume of the part, but utilization
is then defaulted to 86% to account for dead area, since any given cylinder
is assumed to have multiple capsule tanks "inside" it.

So tldr assign volume equal to actual volume and let RF do the rest

Sent by my thumbs, slowly.

**Comment by PhineasFreak** [comment]
OK, i updated the values for the smaller tanks but i am still having doubts about the nose cone fuselage. RO itself sets the overall volume to 1200 L, so even the 1400 L that i have here seem too much.

Thank you everyone for the notes about model --> volume utilization! I was aware about the "filleted" cylinders representing the separate fuel and oxidizer tanks but i was not sure if that covered any other hardware apart from the end domes/stringers. Now i know better...

**Comment by Starwaster** [comment]
Ok so it looks like we're done here or were there more part patches coming @PhineasFreak ? Should we go ahead and merge?

**Comment by PhineasFreak** [comment]
I do not think that KSP 1.5 added/changed tanks so these will suffice for now.

**Comment by blowfishpro** [comment]
I think some of the new tanks are really new parts, with the old ones kept around but hidden for compatibility.  But we can deal with that later.

**Pull request merged**
