### PR TITLE
NF Propulsion fuel tanks

### PR DESCRIPTION
**Pull request by Tellion**

### CODE REVIEW

**Comment by NathanKell** [comment]
@Tellion um...hydrazine requires a highly-pressurized tank. "Default" is not a highly pressurized tank. That's why it's not in anything but type SM or Fuselage (the two highly-pressurized tank types).

Question on the NF parts: did you make their masses the same as a proc part of the diameter of the part and length of the part (as I believe you may have indicated before), or a _set_ of proc parts that volumetrically match the NF part? I..e the NF part is a central core with lots of spheres, make a proc structural cylinder of the appropriate inner diameter, then surf-attach a fillet cylinder and change its radius/length/fillet to make it a sphere of the right size, and multiply _that_ part's volume by the number of spheres.
I mentioned that in the prior PR but didn't hear back, so poking again :]

**Comment by Tellion** [comment]
Ah, right then, ignore that. I just concluded from the availability of UDMH, AZ50 etc in the default tanktype  that it was left out. 

The former, right now all parts basically behave like a PP part with their outer dimensions. The reason I went with this (apart from not trusting my eyes too much) is that the RF electrical propulsion tank type allows most of the noble gases, so giving the xenon tanks a smaller, if visually appropriate volume would render them the inferior choice compared to an argon tank and/or proc parts tanks - you could essentially always get more fuel for the same size by not using them. 

If there is a physical reason for those differences in tank volume, handling things via the utilization parameter for the xenon tank definition might be a better way, that would balance things across the board.

**Comment by NathanKell** [comment]
I'm sorry, I'm not exactly following -- Don't all the NF tanks get set to ElectricalPropulsion? And yeah, collections of spheres are kinda sucky from a volume-utilization perspective, but that probably should be dealt with by cost balancing rather than by artificially increasing their volume. Unless I'm misunderstanding?

**Comment by Tellion** [comment]
They do, which means an Argon tank with objectively more volume will be better at storing Xenon than a Xenon tank that is an array of spheres. To avoid that, volume is based on part dimensions - alternatives are either changing the RF tank utilization parameter or going back to dedicated tanks (without RF tank modules). Would you solve this differently?

**Comment by NathanKell** [comment]
For my part, I'd just name the tank with objectively more tankage "Large Electric Propulsion tank" and the smaller one "Small". IMO RF should be in the business of establishing what volume a part would actually have, and then configuring for that, rather than balancing based on cost or total bounding box volume (especially since RF will calculate mass based on tank volume, so the tank with lower volume will have a lower mass)..

**Comment by NathanKell** [comment]
It's probably also worth pinging @ChrisAdderley on this. :)

**Comment by Tellion** [comment]
We can do that, but I fear that there will be no gameplay reason to use the "Small" Tanks - they will always underperform for a given part size. Even using PP parts would always be superior to them... It seems like a waste to discourage use of parts that have so much quality.

**Comment by NathanKell** [comment]
That's why I suggested lowering their cost. The other thing you could do is override their basemass, making them slightly more efficient mass-wise though less efficient in terms of volume utilization.

**Comment by Tellion** [comment]
Ah, sry, that passed me. That sounds like a decent solution, let's go for that. The numbers I would choose would be pretty arbitrary though, something like 10-20% better dry:wet mass ratio, and something like 50% of the cost. Any suggestions on that?

**Comment by NathanKell** [comment]
That seems very reasonable to me! Spherical pressure vessels, AFAIK, will have the best mass:volume ratio...
You'd determine the basemass by loading the part as is, then set basemass = (that * 0.85) in the MODULE, like basemass = 0.085 (if the base mass ingame were 0.1, i.e. 100kg)

**Comment by Tellion** [comment]
Alright, that should do. I managed to replicate the arrays surprisingly well in the end, volumes are set accordingly now. The reduced basemasses only make up a tiny fraction of dry weight in a filled state leading to the mass fractions being only marginally better, but everything seems to behave as expected. I modified costs to encourage use of the array tanks but costs in general seem to be all over the place in KSP so no claims of balance in that regard. I also tried to remove references to specific tank contents as much as possible, leaving only the name prefixes (HI, AR, XE) for a little bit of individuality in the names. Apart from that, tanks are suffixed by either "Cryogenic Fuel Tank" or "Electric Propulsion Tank". At last,  Hydrazine is also gone from default again. Let me know if I missed anything!

**Comment by NathanKell** [comment]
Awesome!

**Pull request merged**
